import { RailType } from "data/RailType";
import { ItemBridgeCreator } from "item/ItemBridgeCreator";
import { ItemLiftButtonsLinkModifier } from "item/ItemLiftButtonsLinkModifier";
import { ItemLiftRefresher } from "item/ItemLiftRefresher";
import { ItemRailModifier } from "item/ItemRailModifier";
import { ItemSignalModifier } from "item/ItemSignalModifier";
import { ItemTunnelCreator } from "item/ItemTunnelCreator";
import { ItemTunnelWallCreator } from "item/ItemTunnelWallCreator";
import { DyeColor } from "util/DyeColor";

export namespace Items {

	export const LIFT_BUTTONS_LINK_CONNECTOR = new ItemLiftButtonsLinkModifier(true);
	export const LIFT_BUTTONS_LINK_REMOVER = new ItemLiftButtonsLinkModifier(false);
	export const LIFT_REFRESHER = new ItemLiftRefresher();
    export const RAIL_CONNECTOR_20 = new ItemRailModifier(true, false, true, false, RailType.WOODEN);
    export const RAIL_CONNECTOR_20_ONE_WAY = new ItemRailModifier(true, false, true, true, RailType.WOODEN);
    export const RAIL_CONNECTOR_40 = new ItemRailModifier(true, false, true, false, RailType.STONE);
    export const RAIL_CONNECTOR_40_ONE_WAY = new ItemRailModifier(true, false, true, true, RailType.STONE);
    export const RAIL_CONNECTOR_60 = new ItemRailModifier(true, false, true, false, RailType.EMERALD);
    export const RAIL_CONNECTOR_60_ONE_WAY = new ItemRailModifier(true, false, true, true, RailType.EMERALD);
    export const RAIL_CONNECTOR_80 = new ItemRailModifier(true, false, true, false, RailType.IRON);
    export const RAIL_CONNECTOR_80_ONE_WAY = new ItemRailModifier(true, false, true, true, RailType.IRON);
    export const RAIL_CONNECTOR_120 = new ItemRailModifier(true, false, true, false, RailType.OBSIDIAN);
    export const RAIL_CONNECTOR_120_ONE_WAY = new ItemRailModifier(true, false, true, true, RailType.OBSIDIAN);
    export const RAIL_CONNECTOR_160 = new ItemRailModifier(true, false, true, false, RailType.BLAZE);
    export const RAIL_CONNECTOR_160_ONE_WAY = new ItemRailModifier(true, false, true, true, RailType.BLAZE);
    export const RAIL_CONNECTOR_200 = new ItemRailModifier(true, false, true, false, RailType.QUARTZ);
    export const RAIL_CONNECTOR_200_ONE_WAY = new ItemRailModifier(true, false, true, true, RailType.QUARTZ);
    export const RAIL_CONNECTOR_300 = new ItemRailModifier(true, false, true, false, RailType.DIAMOND);
    export const RAIL_CONNECTOR_300_ONE_WAY = new ItemRailModifier(true, false, true, true, RailType.DIAMOND);
    export const RAIL_CONNECTOR_PLATFORM = new ItemRailModifier(true, true, true, false, RailType.PLATFORM);
    export const RAIL_CONNECTOR_SIDING = new ItemRailModifier(true, true, true, false, RailType.SIDING);
    export const RAIL_CONNECTOR_TURN_BACK = new ItemRailModifier(true, false, true, false, RailType.TURN_BACK);
	export const RAIL_REMOVER = new ItemRailModifier();
	export const SIGNAL_CONNECTOR_WHITE = new ItemSignalModifier(true, DyeColor.WHITE);
	export const SIGNAL_CONNECTOR_ORANGE = new ItemSignalModifier(true, DyeColor.ORANGE);
	export const SIGNAL_CONNECTOR_MAGENTA = new ItemSignalModifier(true, DyeColor.MAGENTA);
	export const SIGNAL_CONNECTOR_LIGHT_BLUE = new ItemSignalModifier(true, DyeColor.LIGHT_BLUE);
	export const SIGNAL_CONNECTOR_YELLOW = new ItemSignalModifier(true, DyeColor.YELLOW);
	export const SIGNAL_CONNECTOR_LIME = new ItemSignalModifier(true, DyeColor.LIME);
	export const SIGNAL_CONNECTOR_PINK = new ItemSignalModifier(true, DyeColor                                                                                                                                                                                                                                                                                                                                                                                                                       .PINK);
	export const SIGNAL_CONNECTOR_GRAY = new ItemSignalModifier(true, DyeColor.GRAY);
	export const SIGNAL_CONNECTOR_LIGHT_GRAY = new ItemSignalModifier(true, DyeColor.LIGHT_GRAY);
	export const SIGNAL_CONNECTOR_CYAN = new ItemSignalModifier(true, DyeColor.CYAN);
	export const SIGNAL_CONNECTOR_PURPLE = new ItemSignalModifier(true, DyeColor.PURPLE);
	export const SIGNAL_CONNECTOR_BLUE = new ItemSignalModifier(true, DyeColor.BLUE);
	export const SIGNAL_CONNECTOR_BROWN = new ItemSignalModifier(true, DyeColor.BROWN);
	export const SIGNAL_CONNECTOR_GREEN = new ItemSignalModifier(true, DyeColor.GREEN);
	export const SIGNAL_CONNECTOR_RED = new ItemSignalModifier(true, DyeColor.RED);
	export const SIGNAL_CONNECTOR_BLACK = new ItemSignalModifier(true, DyeColor.BLACK);
	export const SIGNAL_REMOVER_WHITE = new ItemSignalModifier(false, DyeColor.WHITE);
	export const SIGNAL_REMOVER_ORANGE = new ItemSignalModifier(false, DyeColor.ORANGE);
	export const SIGNAL_REMOVER_MAGENTA = new ItemSignalModifier(false, DyeColor.MAGENTA);
	export const SIGNAL_REMOVER_LIGHT_BLUE = new ItemSignalModifier(false, DyeColor.LIGHT_BLUE);
	export const SIGNAL_REMOVER_YELLOW = new ItemSignalModifier(false, DyeColor.YELLOW);
	export const SIGNAL_REMOVER_LIME = new ItemSignalModifier(false, DyeColor.LIME);
	export const SIGNAL_REMOVER_PINK = new ItemSignalModifier(false, DyeColor.PINK);
	export const SIGNAL_REMOVER_GRAY = new ItemSignalModifier(false, DyeColor.GRAY);
	export const SIGNAL_REMOVER_LIGHT_GRAY = new ItemSignalModifier(false, DyeColor.LIGHT_GRAY);
	export const SIGNAL_REMOVER_CYAN = new ItemSignalModifier(false, DyeColor.CYAN);
	export const SIGNAL_REMOVER_PURPLE = new ItemSignalModifier(false, DyeColor.PURPLE);
	export const SIGNAL_REMOVER_BLUE = new ItemSignalModifier(false, DyeColor.BLUE);
	export const SIGNAL_REMOVER_BROWN = new ItemSignalModifier(false, DyeColor.BROWN);
	export const SIGNAL_REMOVER_GREEN = new ItemSignalModifier(false, DyeColor.GREEN);
	export const SIGNAL_REMOVER_RED = new ItemSignalModifier(false, DyeColor.RED);
	export const SIGNAL_REMOVER_BLACK = new ItemSignalModifier(false, DyeColor.BLACK);
	export const BRIDGE_CREATOR_3 = new ItemBridgeCreator(3);
	export const BRIDGE_CREATOR_5 = new ItemBridgeCreator(5);
	export const BRIDGE_CREATOR_7 = new ItemBridgeCreator(7);
	export const BRIDGE_CREATOR_9 = new ItemBridgeCreator(9);
	export const TUNNEL_CREATOR_4_3 = new ItemTunnelCreator(4, 3);
	export const TUNNEL_CREATOR_4_5 = new ItemTunnelCreator(4, 5);
	export const TUNNEL_CREATOR_4_7 = new ItemTunnelCreator(4, 7);
	export const TUNNEL_CREATOR_4_9 = new ItemTunnelCreator(4, 9);
	export const TUNNEL_CREATOR_5_3 = new ItemTunnelCreator(5, 3);
	export const TUNNEL_CREATOR_5_5 = new ItemTunnelCreator(5, 5);
	export const TUNNEL_CREATOR_5_7 = new ItemTunnelCreator(5, 7);
	export const TUNNEL_CREATOR_5_9 = new ItemTunnelCreator(5, 9);
	export const TUNNEL_CREATOR_6_3 = new ItemTunnelCreator(6, 3);
	export const TUNNEL_CREATOR_6_5 = new ItemTunnelCreator(6, 5);
	export const TUNNEL_CREATOR_6_7 = new ItemTunnelCreator(6, 7);
	export const TUNNEL_CREATOR_6_9 = new ItemTunnelCreator(6, 9);
	export const TUNNEL_WALL_CREATOR_4_3 = new ItemTunnelWallCreator(4, 3);
	export const TUNNEL_WALL_CREATOR_4_5 = new ItemTunnelWallCreator(4, 5);
	export const TUNNEL_WALL_CREATOR_4_7 = new ItemTunnelWallCreator(4, 7);
	export const TUNNEL_WALL_CREATOR_4_9 = new ItemTunnelWallCreator(4, 9);
	export const TUNNEL_WALL_CREATOR_5_3 = new ItemTunnelWallCreator(5, 3);
	export const TUNNEL_WALL_CREATOR_5_5 = new ItemTunnelWallCreator(5, 5);
	export const TUNNEL_WALL_CREATOR_5_7 = new ItemTunnelWallCreator(5, 7);
	export const TUNNEL_WALL_CREATOR_5_9 = new ItemTunnelWallCreator(5, 9);
	export const TUNNEL_WALL_CREATOR_6_3 = new ItemTunnelWallCreator(6, 3);
	export const TUNNEL_WALL_CREATOR_6_5 = new ItemTunnelWallCreator(6, 5);
	export const TUNNEL_WALL_CREATOR_6_7 = new ItemTunnelWallCreator(6, 7);
	export const TUNNEL_WALL_CREATOR_6_9 = new ItemTunnelWallCreator(6, 9);
}