name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx tsc --version
    - run: npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-mcaddon-output-${{ matrix.node-version }}
        path: build/*.mcaddon

